### PR TITLE
solution difference es5 and es-next

### PR DESCRIPTION
**Pull request by II-alex-II**
Hi @anseki,
Take the MR, it makes the difference es5 and es-next minimal.
It works

### CODE REVIEW

**Comment by anseki** [comment]
Hi @II-alex-II, thank you for the PR.
Could you publish type definition on DefinitelyTyped?
Thank you for your time. :smile:

**Comment by II-alex-II** [comment]
I can publish type definition on DefinitelyTyped,  you could code add?
`(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
    typeof define === 'function' && define.amd ? define(factory) :
      (global['leader-line'] = factory());
}(this, (function () {
 return LeaderLine;
})));`

**Comment by anseki** [comment]
LeaderLine is old now. You should've seen many legacy codes in the source code.
I think that the code should be rewritten for modern code, structure and mechanism before supporting importing if the library do that. (I think that replacing all of code may need time.)
Of course you can do that if you want.
I don't want to make the code be a mess before the rewriting.

**Comment by II-alex-II** [comment]
Ok, I created alternative https://www.npmjs.com/package/leader-line-new and example use https://github.com/II-alex-II/react-leader-line, today I will move code all  my PR

**Comment by anseki** [comment]
Thank you! :smile:

**Comment by II-alex-II** [comment]
Thank you! You could help contribute to creating a new version?

**Comment by anseki** [comment]
Yes, I will contribute that if I can.

**Comment by BrianAKass** [comment]
Hey there passing through and spotted this library for a project im working on.  Are you two still developing an update?

**Comment by anseki** [comment]
Hi @BrianAKass, thank you for the comment.
We are not writing the type definition and module.

**Comment by BrianAKass** [comment]
Thanks I am using react-xarrows https://eliav2.github.io/react-xarrows/ in the meantime. Fits my needs so im good for now.

**Comment by anseki** [comment]
:smile:

**Pull request closed without merging**
