### PR TITLE
let-line-go-through-element-center

### PR DESCRIPTION
**Pull request by davidwang1988**

### CODE REVIEW

**Comment by anseki** [comment]
Hi @davidwang1988, thank you for the PR.
This seems incomplete.

**Comment by davidwang1988** [comment]
You may have a try. I have used this in my project and it works.




On 08/16/2020 21:56, anseki wrote:

Closed #155.

**Comment by anseki** [comment]
Could you explain that?

**Comment by davidwang1988** [comment]
The code could figure out the start and end points' coordinate instead of the 8 possible points which provided in current code.
Through the two points the leaderline will go through the centers of the two elements.
Especially, it looks very nice when the two elements are border radius 50%




On 08/17/2020 13:08, anseki wrote:

Could you explain that?

**Comment by davidwang1988** [comment]
My code may need optimization, but the feature - go through element center, is useful and required in my opinion




On 08/17/2020 13:30, DavidWang wrote:
The code could figure out the start and end points' coordinate instead of the 8 possible points which provided in current code.
Through the two points the leaderline will go through the centers of the two elements.
Especially, it looks very nice when the two elements are border radius 50%




On 08/17/2020 13:08, anseki wrote:

Could you explain that?

**Comment by anseki** [comment]
Do you mean that the PR makes the line connect to center of specific element instead of specifying `startSocket`/`endSocket` options?

**Pull request closed without merging**
